### ISSUE TITLE
Confidence values

### ISSUE THREAD

**Issue by AlphaSquad** [CAMI-challenge/CAMITAX#12]
It might be useful to have some kind of confidence values of the tools (if they provide it internally). 
I have seen the following example for one of the (new) genomes:
The LCA of tools was bacteria (TaxID 2), which was caused by a single conflicting assignment:
Mash, Kaiju as well as Centrifuge all predicted a Psychrobacter, CheckM predicted bacteria, only dada2 predicted a Chryseobacterium which is of a different phylum than Psychrobacter. If the dada2 prediction is not really confident, one could decide to go with the matching prediction of the other 3.

**Comment by abremges** [comment]
Can you provide me with the genome ID please, such that I can manually inspect the assignments?
I'm a bit surprised, because I already require a bootstrap support of 80/100 for Dada2 assignments.

**Comment by abremges** [comment]
(Also, it's not LCA but the lowest consistent assignment.) 😛

**Comment by abremges** [comment]
Not feasible to expose & individual tool assignments are available in the output folders.
