### ISSUE TITLE
warning process name deprecated

### ISSUE THREAD

**Issue by arianccbasile** [CAMI-challenge/CAMITAX#15]
Dear Andreas,
I have installed CAMITAX usin "nextflow /docker". Installation completed successfully but the process stops with the warning reported below.
Thanks in advance

Input genomes:
WARN: Process configuration syntax $processName has been deprecated -- Replace `process.$mash = <value>` with a process selector
[warm up] executor > local
WARN: Process configuration syntax $processName has been deprecated -- Replace `process.$checkm = <value>` with a process selector
WARN: Process configuration syntax $processName has been deprecated -- Replace `process.$dada2 = <value>` with a process selector
WARN: Process configuration syntax $processName has been deprecated -- Replace `process.$prodigal = <value>` with a process selector
WARN: Process configuration syntax $processName has been deprecated -- Replace `process.$centrifuge = <value>` with a process selector
WARN: Process configuration syntax $processName has been deprecated -- Replace `process.$kaiju = <value>` with a process selector

**Comment by abremges** [comment]
Thank you, @arianccbasile – I was using an outdated Nextflow version.

Apparently, the containers definitions changed recently, as described here:
https://www.nextflow.io/docs/latest/docker.html#multiple-containers

I just applied a hotfix, hopefully this solved the issue. Please try again.
Unfortunately I couldn't test it, yet, but will do so first thing tomorrow.

Thanks again! /A

**Comment by arianccbasile** [comment]
Dear Andreas,
I fixed the nextflow.config file as suggested.
Using the command line 
NXF_VER=0.28.0 nextflow run abremges/CAMITAX --db /mnt/data_HDD/databases/CAMITAX_db/ --i /mnt/data_HDD/stefano/progetto_yifeng_rusen/BIN_REFINEMENT/metaWRAP_bins/ --x fa
I have the following error:

`WARN: Unknown directive `centrifuge` for process `mash`
WARN: Unknown directive `checkm` for process `mash`
WARN: Unknown directive `dada2` for process `mash`
WARN: Unknown directive `kaiju` for process `mash`
WARN: Unknown directive `mash` for process `mash`
WARN: Unknown directive `prodigal` for process `mash`
[warm up] executor > local
WARN: Unknown directive `centrifuge` for process `checkm`
WARN: Unknown directive `checkm` for process `checkm`
WARN: Unknown directive `dada2` for process `checkm`
WARN: Unknown directive `kaiju` for process `checkm`
WARN: Unknown directive `mash` for process `checkm`
WARN: Unknown directive `prodigal` for process `checkm`
WARN: Unknown directive `centrifuge` for process `dada2`
WARN: Unknown directive `checkm` for process `dada2`
WARN: Unknown directive `dada2` for process `dada2`
WARN: Unknown directive `kaiju` for process `dada2`
WARN: Unknown directive `mash` for process `dada2`
WARN: Unknown directive `prodigal` for process `dada2`
WARN: Unknown directive `centrifuge` for process `prodigal`
WARN: Unknown directive `checkm` for process `prodigal`
WARN: Unknown directive `dada2` for process `prodigal`
WARN: Unknown directive `kaiju` for process `prodigal`
WARN: Unknown directive `mash` for process `prodigal`
WARN: Unknown directive `prodigal` for process `prodigal`
WARN: Unknown directive `centrifuge` for process `centrifuge`
WARN: Unknown directive `checkm` for process `centrifuge`
WARN: Unknown directive `dada2` for process `centrifuge`
WARN: Unknown directive `kaiju` for process `centrifuge`
WARN: Unknown directive `mash` for process `centrifuge`
WARN: Unknown directive `prodigal` for process `centrifuge`
WARN: Unknown directive `centrifuge` for process `kaiju`
WARN: Unknown directive `checkm` for process `kaiju`
WARN: Unknown directive `dada2` for process `kaiju`
WARN: Unknown directive `kaiju` for process `kaiju`
WARN: Unknown directive `mash` for process `kaiju`
WARN: Unknown directive `prodigal` for process `kaiju`
WARN: Unknown directive `centrifuge` for process `taxonomy`
WARN: Unknown directive `checkm` for process `taxonomy`
WARN: Unknown directive `dada2` for process `taxonomy`
WARN: Unknown directive `kaiju` for process `taxonomy`
WARN: Unknown directive `mash` for process `taxonomy`
WARN: Unknown directive `prodigal` for process `taxonomy`
WARN: Unknown directive `centrifuge` for process `summary`
WARN: Unknown directive `checkm` for process `summary`
WARN: Unknown directive `dada2` for process `summary`
WARN: Unknown directive `kaiju` for process `summary`
WARN: Unknown directive `mash` for process `summary`
WARN: Unknown directive `prodigal` for process `summary`
[93/f2c001] Submitted process > checkm (bin.26)
[eb/55232c] Submitted process > checkm (bin.27)
[39/409739] Submitted process > checkm (bin.19)
[fa/c80ed6] Submitted process > mash (bin.33)
[d4/3422f0] Submitted process > prodigal (bin.12)
[bb/ce711a] Submitted process > mash (bin.11)
[0c/4cb763] Submitted process > mash (bin.14)
[4a/41782a] Submitted process > checkm (bin.16)
[f3/462545] Submitted process > mash (bin.18)
[55/456fa3] Submitted process > prodigal (bin.10)
[46/198e5f] Submitted process > mash (bin.32)
[6c/c16449] Submitted process > prodigal (bin.23)
[e7/2c93dd] Submitted process > mash (bin.8)
[f0/253456] Submitted process > prodigal (bin.20)
[4a/570345] Submitted process > mash (bin.30)
[31/c884e1] Submitted process > prodigal (bin.36)
[7a/a1dd46] Submitted process > prodigal (bin.3)
[90/9c1dbb] Submitted process > mash (bin.17)
[62/b6c2f0] Submitted process > mash (bin.36)
[90/1053e3] Submitted process > mash (bin.40)
ERROR ~ Error executing process > 'checkm (bin.26)'

Caused by:
  Process `checkm (bin.26)` terminated with an error exit status (127)

Command executed:

  # Set CheckM root data location
  echo CAMITAX_db/checkm/ | checkm data setRoot CAMITAX_db/checkm/
  
  # Extract 16S rRNA gene sequences with Nhmmer
  checkm ssu_finder -t 8 -x fa bin.26.fa . ssu_finder 2>&1
  ln -s ssu_finder/ssu.fna bin.26.ssu.fna
  
  # Phylogenetic placement onto reduced reference tree
  checkm lineage_wf -t 8 --reduced_tree -x fa . checkm
  checkm qa -o 2 --tab_table checkm/lineage.ms checkm > bin.26.checkm.tsv

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 3: checkm: command not found

Work dir:
  /mnt/data_HDD/databases/CAMITAX_db/work/93/f2c0012f5c9c694e2924f50e25116f

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
WARN: Killing pending tasks (19)`

*************************************************************
using "nextflow version 19.01.0.5050" and running the command line below:
nextflow run abremges/CAMITAX --db /mnt/data_HDD/databases/CAMITAX_db/ --i /mnt/data_HDD/stefano/progetto_yifeng_rusen/BIN_REFINEMENT/metaWRAP_bins/ --x fa

the error is the following:
`[warm up] executor > local
[7d/7cbea0] Submitted process > checkm (bin.38)
[77/2530d3] Submitted process > checkm (bin.13)
[33/3e1d4a] Submitted process > checkm (bin.29)
[73/476716] Submitted process > prodigal (bin.22)
[c2/bbdec8] Submitted process > checkm (bin.25)
[71/78cc90] Submitted process > prodigal (bin.8)
[d6/65a3f8] Submitted process > mash (bin.17)
[ee/a139fa] Submitted process > prodigal (bin.28)
[fd/b6cf73] Submitted process > mash (bin.13)
[05/d7ec33] Submitted process > prodigal (bin.11)
[80/4dba73] Submitted process > mash (bin.32)
[60/0bfb7c] Submitted process > mash (bin.9)
[f9/1543ae] Submitted process > checkm (bin.8)
ERROR ~ Error executing process > 'checkm (bin.38)'

Caused by:
  Process `checkm (bin.38)` terminated with an error exit status (126)

Command executed:

  # Set CheckM root data location
  echo CAMITAX_db/checkm/ | checkm data setRoot CAMITAX_db/checkm/
  
  # Extract 16S rRNA gene sequences with Nhmmer
  checkm ssu_finder -t 8 -x fa bin.38.fa . ssu_finder 2>&1
  ln -s ssu_finder/ssu.fna bin.38.ssu.fna
  
  # Phylogenetic placement onto reduced reference tree
  checkm lineage_wf -t 8 --reduced_tree -x fa . checkm
  checkm qa -o 2 --tab_table checkm/lineage.ms checkm > bin.38.checkm.tsv

Command exit status:
  126

Command output:
  (empty)

Command error:
  docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.35/containers/create?name=nxf-0kcjDa9jjL0JByGyefmrGN8K: dial unix /var/run/docker.sock: connect: permission denied.
  See 'docker run --help'.

Work dir:
  /mnt/data_HDD/databases/CAMITAX_db/work/7d/7cbea047c081cc0a1109144c40f56d

Tip: when you have fixed the problem you can continue the execution appending to the nextflow command line the option `-resume`

 -- Check '.nextflow.log' file for details
WARN: Killing pending tasks (11)`


Thanks in advance for your support!!

**Comment by abremges** [comment]
Thank you, @arianccbasile. It indeed shouldn't work when using `NXF_VER=0.28.0`, because the container definitions were changed thereafter (this should work with the older CAMITAX version, by the way, before I applied the hotfix). Anyway...

The second issue, running on Nextflow v19.01.0.5050, sounds like a more general Docker issue. Please try to execute a simple `docker run hello-world` on your machine. If this works, I'll have to further investigate. Else it appears to be a Docker problem on your end, please check for instance: https://techoverflow.net/2017/03/01/solving-docker-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket/

**Comment by AlphaSquad** [comment]
Tested the current version of CAMITAX with Nextflow 19.01.0, it was running on a Debian 8.10 machine without error or warning

**Comment by abremges** [comment]
Thank you, @AlphaSquad, for testing and confirming that everything works (again).

I'm closing this issue now, @arianccbasile, please re-open if you feel so. If Docker continues to cause trouble, use Singularity or install all dependencies using bioconda. Both options are outlined in the README but note that you need to provide a local nextflow.config then: https://www.nextflow.io/docs/latest/config.html

Thanks again, @arianccbasile, for this issue. I definitely learned something new again, based on that we can improve CAMITAX in future versions...

**Comment by arianccbasile** [comment]
Thank you @abremges and @AlphaSquad for all the support. It was indeed a problem of Docker, we solved it with https://techoverflow.net/2017/03/01/solving-docker-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket/ help and after that it worked properly. 

Sincerely,
Arianna Basile

**Comment by abremges** [comment]
Great to hear! If you have any questions or feedback,  @arianccbasile, please feel free to drop me an email or write here. 👍
